src/Entity/Dog.php
<?php

namespace App\Entity;

use App\Repository\DogRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DogRepository::class)]
class Dog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?\DateTime $birth_date = null;

    #[ORM\Column(length: 255)]
    private ?string $sex = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $identity_number = null;

    #[ORM\ManyToOne(inversedBy: 'dogs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    /**
     * @var Collection<int, WalkRegistration>
     */
    #[ORM\OneToMany(targetEntity: WalkRegistration::class, mappedBy: 'dog')]
    private Collection $walk_registration;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    #[ORM\ManyToOne(inversedBy: 'dogs')]
    private ?DogBreed $dogBreed = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    public function __construct()
    {
        $this->walk_registration = new ArrayCollection();
        $this->status = "Active";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getBirthDate(): ?\DateTime
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTime $birth_date): static
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getAge(): ?int
    {
        $birthDate = $this->getBirthDate();
        if ($birthDate) {
            $now = new DateTime('now');
            $bd = $birthDate->getTimestamp();
            $nowb = $now->getTimestamp();
            $age = ($nowb - $bd) / (365 * 24 * 60 * 60);
            return $age;
        } else {
            return null;
        }
    }

    public function getAgeM(): ?int
    {
        $birthDate = $this->getBirthDate();
        if ($birthDate) {
            $now = new DateTime('now');
            $bd = $birthDate->getTimestamp();
            $nowb = $now->getTimestamp();
            $age = ($nowb - $bd) / ((365 / 12) * 24 * 60 * 60);
            return $age;
        } else {
            return null;
        }
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): static
    {
        $this->sex = $sex;

        return $this;
    }

    public function getIdentityNumber(): ?string
    {
        return $this->identity_number;
    }

    public function setIdentityNumber(?string $identity_number): static
    {
        $this->identity_number = $identity_number;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, WalkRegistration>
     */
    public function getWalkRegistration(): Collection
    {
        return $this->walk_registration;
    }

    public function addWalkRegistration(WalkRegistration $walkRegistration): static
    {
        if (!$this->walk_registration->contains($walkRegistration)) {
            $this->walk_registration->add($walkRegistration);
            $walkRegistration->setDog($this);
        }

        return $this;
    }

    public function removeWalkRegistration(WalkRegistration $walkRegistration): static
    {
        if ($this->walk_registration->removeElement($walkRegistration)) {
            // set the owning side to null (unless already changed)
            if ($walkRegistration->getDog() === $this) {
                $walkRegistration->setDog(null);
            }
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDogBreed(): ?DogBreed
    {
        return $this->dogBreed;
    }

    public function setDogBreed(?DogBreed $dogBreed): static
    {
        $this->dogBreed = $dogBreed;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Dog;
use App\Entity\Walk;
use App\Entity\Trail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class ProfileController extends AbstractController
{
    #[Route('/profile', name: 'app_profile', methods: ['GET'])]
    public function index(): Response
    {
        $user = $this->getUser();
        if (!$user instanceof User) {
            return $this->redirectToRoute('app_login');
        }
        $trails = $user->getTrails();
        $dogs = $user->getDogs();

        $walkRegistrations = [];
        foreach ($dogs as $dog) {

            $wrs = $dog->getWalkRegistration();
            foreach ($wrs as $wr) {
                $walkRegistrations[] = $wr;
            }
        }
        return $this->render('profile/index.html.twig', [
            'user' => $user,
            'trails' => $trails,
            'dogs' => $dogs,
            'walkRegistrations' => $walkRegistrations
        ]);
    }
}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon profil
{% endblock %}

{% block body %}
	<section class="profile">
		<h1 class="profile__title">{{ app.user.title }}
			{{ app.user.firstname }}
			{{ app.user.name }}</h1>


		<div class="profile__user">

			{% if app.user.title %}
				<div class="profile__user-item">
					<p class="profile__user-subtitle">Civilité</p>
					{% set titleFull = {
            'M': 'Monsieur',
            'Mme' :'Madame'}[app.user.title] ?? 'Non renseigné' %}
					<p class="profile__user-content">{{ titleFull }}</p>
				</div>
			{% endif %}

			<div class="profile__user-item">
				<p class="profile__user-subtitle">Prénom</p>
				<p class="profile__user-content">{{ app.user.firstname }}</p>
			</div>
			<div class="profile__user-item">
				<p class="profile__user-subtitle">Nom</p>
				<p class="profile__user-content">{{ app.user.name }}</p>
			</div>
			<div class="profile__user-item">
				<p class="profile__user-subtitle">Adresse email</p>
				<p class="profile__user-content">{{ app.user.email }}</p>
			</div>

			<a class="profile__button" href="{{ path('admin_user_edit', {'id': app.user.id}) }}">Modifier</a>
		</div>

		<h2 class="profile__title">Historique</h2>
		<div class="profile__nav">
			<ul class="profile__list">
				<li class="profile__list-item">
					<a href="{{ path('app_profile', {'section': 'dogs'}) }}" class="profile__list-link">{{ ux_icon('mdi:paw', {class: 'profile__icon'}) }}
						Mes chiens</a>
				</li>
				<li class="profile__list-item">
					<a href="{{ path('app_profile', {'section': 'trails'}) }}" class="profile__list-link">{{ ux_icon('streamline:arrow-roadmap', {class: 'profile__icon'}) }}
						Mes itinéraires</a>
				</li>
				<li class="profile__list-item">
					<a href="{{ path('app_profile', {'section': 'walksr'}) }}" class="profile__list-link">{{ ux_icon('fa7-solid:dog', {class: 'profile__icon'}) }}
						Mes balades</a>
				</li>

			</ul>
		</div>

		{% if app.request.query.get('section') == 'dogs' or app.request.query.get('section') is null %}
			<div class="profile__dogs">
				{% if dogs %}
					{% for dog in dogs %}
								{% if dog.photo and dog.sex == "female" %}
								<img class="profile__dog-photo-female" src="{{ asset('uploads/images/' ~ dog.photo)}}">
								{% elseif dog.photo and dog.sex == "male" %}
								<img class="profile__dog-photo-male" src="{{ asset('uploads/images/' ~ dog.photo)}}">
								{% elseif (not dog.photo) and dog.sex == "female" %}
								{{ux_icon('streamline-plump:dog-1-remix', {class: 'profile__dog-photo-female'})}}
								{% elseif (not dog.photo) and dog.sex == "male" %}
								{{ux_icon('streamline-plump:dog-1-remix', {class: 'profile__dog-photo-male'})}}
						{% endif %}
						<p class="profile__dog-content">{{ dog.name }}</p>
						{% if dog.birthDate and dog.age >= 1 %}
							<p class="profile__dog-content">{{ dog.age }}
								an{{ dog.age > 1 ? "s" : "" }}</p>
						{% endif %}
						{% if dog.birthDate and dog.age == 0 and dog.ageM >= 1 %}
							<p class="profile__dog-content">{{ dog.ageM }}
								mois</p>
						{% endif %}

						{% if dog.birthDate and dog.age > 0 and dog.ageM > 0 %}
							<p class="profile__dog-content">{{ dog.ageM - (dog.age * 12) }}
								mois</p>
						{% endif %}
						{% if dog.dogBreed %}
							{% for breed in dog.dogBreed %}
								<p class="profile__dog-content">{{ dog.dogBreed|join('') }}</p>
							{% endfor %}
						{% endif %}
						{% if dog.identityNumber %}
							<p class="profile__dog-content">{{ dog.identityNumber }}</p>
						{% endif %}

						<div class="profile__dog-wrapper">
							<a class="profile__button" href="{{ path('app_dog_edit', {'id': dog.id}) }}">Modifier</a>
							<form method="post" class="profil__dog-form-delete" action="{{ path('app_dog_inactive', { 'id': dog.id }) }}">
								<button type="submit" class="profil__dog-button-delete">{{ ux_icon('streamline-ultimate:bin-1-bold', {'class': 'profile__dog-delete-icon'}) }}</button>
							</form>
						</div>
					{% endfor %}
				{% endif %}
			</div>
		{% elseif app.request.query.get('section') == 'trails' %}
			<div class="profile__trails">
				{% if trails %}
					{% for trail in trails %}
						<div class="profile__trail-card">
							{% if trail.photos|length > 0 %}
								<img class="profile__trail-photo" src="{{ asset('uploads/images/' ~ trail.photos[0].name) }}" alt="Photo de l'itinéraire {{ trail.name }}">
							{% else %}
								{{ux_icon('f7:photo', {class: 'profile__trail-photo'})}}
							{% endif %}
							<p class="profile__trail-name">
								<strong>{{ trail.name }}</strong>
							</p>

							<div class="profile__trail-description">
								<div class="profile__trail-item">
									{{ux_icon('material-symbols:distance-rounded', {class: 'profile__trail-icon'})}}
									<p class="profile__trail-content">{{ trail.startCity }}
									</p>
								</div>
								<div class="profile__trail-description">
									<div class="profile__trail-item">
										{{ux_icon('game-icons:path-distance', {class: 'profile__trail-icon'})}}
										<p class="profile__trail-content">{{ trail.distance|round }}
											km{{ trail.distance > 1 ? "s" : "" }}</p>
									</div>
									<div class="profile__trail-item">
										{{ux_icon('mingcute:time-fill', {class: 'profile__trail-icon'})}}
										<p class="profile__trail-content">{% import 'macros/duration.html.twig' as dur %}
											{{ dur.minutes(trail.duration) }}</p>
									</div>
									<div class="profile__trail-item">
										{{ux_icon('game-icons:strong', {class: 'profile__trail-icon'})}}

										{% set difficultyLabels = {'easy': 'Facile','medium': 'Moyen','hard': 'Difficile'} %}
										<p class="profile__trail-content">{{ difficultyLabels[trail.difficulty] ?? 'Non défini' }}</p>
									</div>
									{% if trail.score %}
										<div class="profile__trail-item">
											{{ux_icon('mdi:like', {class: 'profile__trail-icon'})}}
											<div class="profile__trail-content">

												{% for i in 1.. trail.score %}
													{{ux_icon('material-symbols:star-rounded', {class: 'profile__trail-score'})}}
												{% endfor %}
												{% for i in 1.. (5 - trail.score) %}
													{{ux_icon('material-symbols:star-outline-rounded', {class: 'profile__trail-score'})}}
												{% endfor %}
											</div>
										</div>
									{% endif %}
								</div>

							</div>
							<div class="profile__trail-wrapper">
								<a class="profile__trail-button" href="{{ path('app_trail_show', {id: trail.id}) }}">Consulter l'itinéraire</a>
								<a class="profile__button" href="{{ path('app_trail_edit', {'id': trail.id}) }}">Modifier</a>
								<form method="post" class="profile__trail-form-delete" action="{{ path('app_trail_inactive', { 'id': trail.id }) }}">
									<button type="submit" class="profile__trail-button-delete">{{ ux_icon('streamline-ultimate:bin-1-bold', {'class': 'profile__trail-delete-icon'}) }}</button>
								</form>
							</div>


						</div>
					{% endfor %}
				{% endif %}
			</div>
		{% elseif app.request.query.get('section') == 'walksr' %}
			<div class="profile__walks">
				{% if walkRegistrations %}
					{% for walkRegistration in walkRegistrations %}
						<div class="profile__walks-card">
							<div class="profile__walks-wrapper">
								{% if walkRegistration.dog.photo and walkRegistration.dog.sex == "female" %}
								<img class="profile__walks-photo-female" src="{{ asset('uploads/images/' ~ walkRegistration.dog.photo)}}">
								{% elseif walkRegistration.dog.photo and walkRegistration.dog.sex == "male" %}
								<img class="profile__walks-photo-male" src="{{ asset('uploads/images/' ~ walkRegistration.dog.photo)}}">
								{% elseif (not walkRegistration.dog.photo) and walkRegistration.dog.sex == "female" %}
								{{ux_icon('streamline-plump:dog-1-remix', {class: 'profile__walks-photo-female'})}}
								{% elseif (not walkRegistration.dog.photo) and walkRegistration.dog.sex == "male" %}
								{{ux_icon('streamline-plump:dog-1-remix', {class: 'profile__walks-photo-male'})}}


								{% endif %}
								<p class="profile__walks-content">{{ walkRegistration.dog.name }}</p>
							</div>
							<div class="profile__walks-wrapper">
								<p class="profile__walks-content">{{ walkRegistration.walk.date|format_datetime('full', 'short', locale: 'fr') }}</p>
								<a class="profile__walks-link" href="{{ path('app_trail_show', {id: walkRegistration.walk.trail.id}) }}">{{ walkRegistration.walk.trail.name }}</a>
								<p class="profile__walks-content">{{ walkRegistration.walk.trail.startCity }}</p>
							</div>
						</div>
					{% endfor %}
				{% endif %}
			</div>
		{% endif %}
	</section>
{% endblock %}