src/Entity/Trail.php
<?php

namespace App\Entity;

use App\Repository\TrailRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TrailRepository::class)]
class Trail
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    private ?float $distance = null;

    #[ORM\Column(nullable: true)]
    private ?float $duration = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $difficulty = null;

    #[ORM\Column(nullable: true)]
    private ?float $score = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $water_point = null;

    #[ORM\ManyToOne(inversedBy: 'trails')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    /**
     * @var Collection<int, Walk>
     */
    #[ORM\OneToMany(targetEntity: Walk::class, mappedBy: 'trail')]
    private Collection $walks;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $startAddress = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $startCode = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $startCity = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $endAddress = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $endCode = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $endCity = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nameSearch = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $startCitySearch = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $endCitySearch = null;

    /**
     * @var Collection<int, Photo>
     */
    #[ORM\OneToMany(mappedBy: 'trail', targetEntity: Photo::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection $photos;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $gpxFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $inputMode = null;

    #[ORM\Column(nullable: true)]
    private ?float $startLat = null;

    #[ORM\Column(nullable: true)]
    private ?float $startLon = null;

    #[ORM\Column(nullable: true)]
    private ?float $endLat = null;

    #[ORM\Column(nullable: true)]
    private ?float $endLon = null;

    #[ORM\Column(length: 255)]
    private ?string $Status = null;

    public function __construct()
    {
        $this->walks = new ArrayCollection();
        $this->photos = new ArrayCollection();
        $this->Status = "Active";
    }

    private function normalize(string $value): string
    {
        if ($value === null) {
            return '';
        }
        $value = strtolower($value);
        $value = str_replace(['-', ' ', '_', '.'], '', $value);
        return $value;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;
        $this->nameSearch = $this->normalize($name);
        return $this;
    }

    public function getDistance(): ?float
    {
        return $this->distance;
    }

    public function setDistance(float $distance): static
    {
        $this->distance = $distance;

        return $this;
    }

    public function getDuration(): ?float
    {
        return $this->duration;
    }

    public function setDuration(float $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDifficulty(): ?string
    {
        return $this->difficulty;
    }

    public function setDifficulty(string $difficulty): static
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getScore(): ?float
    {
        return $this->score;
    }

    public function setScore(float $score): static
    {
        $this->score = $score;

        return $this;
    }

    public function getWaterPoint(): ?string
    {
        return $this->water_point;
    }

    public function setWaterPoint(string $water_point): static
    {
        $this->water_point = $water_point;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Walk>
     */
    public function getWalks(): Collection
    {
        return $this->walks;
    }

    public function addWalk(Walk $walk): static
    {
        if (!$this->walks->contains($walk)) {
            $this->walks->add($walk);
            $walk->setTrail($this);
        }

        return $this;
    }

    public function removeWalk(Walk $walk): static
    {
        if ($this->walks->removeElement($walk)) {
            // set the owning side to null (unless already changed)
            if ($walk->getTrail() === $this) {
                $walk->setTrail(null);
            }
        }

        return $this;
    }

    public function getStartAddress(): ?string
    {
        return $this->startAddress;
    }

    public function setStartAddress(string $startAddress): static
    {
        $this->startAddress = $startAddress;

        return $this;
    }

    public function getStartCode(): ?string
    {
        return $this->startCode;
    }

    public function setStartCode(?string $startCode): static
    {
        $this->startCode = $startCode;

        return $this;
    }

    public function getStartCity(): ?string
    {
        return $this->startCity;
    }

    public function setStartCity(?string $startCity): static
    {
        $this->startCity = $startCity;
        $this->startCitySearch = $this->normalize($startCity);
        return $this;
    }

    public function getEndAddress(): ?string
    {
        return $this->endAddress;
    }

    public function setEndAddress(string $endAddress): static
    {
        $this->endAddress = $endAddress;

        return $this;
    }

    public function getEndCode(): ?string
    {
        return $this->endCode;
    }

    public function setEndCode(?string $endCode): static
    {
        $this->endCode = $endCode;

        return $this;
    }

    public function getEndCity(): ?string
    {
        return $this->endCity;
    }

    public function setEndCity(?string $endCity): static
    {
        $this->endCity = $endCity;
        $this->endCitySearch = $this->normalize($endCity);
        return $this;
    }

    public function getNameSearch(): ?string
    {
        return $this->nameSearch;
    }

    public function setNameSearch(string $nameSearch): static
    {
        $this->nameSearch = $nameSearch;

        return $this;
    }

    public function getStartCitySearch(): ?string
    {
        return $this->startCitySearch;
    }

    public function setStartCitySearch(string $startCitySearch): static
    {
        $this->startCitySearch = $startCitySearch;

        return $this;
    }

    public function getEndCitySearch(): ?string
    {
        return $this->endCitySearch;
    }

    public function setEndCitySearch(string $endCitySearch): static
    {
        $this->endCitySearch = $endCitySearch;

        return $this;
    }

    /**
     * @return Collection<int, Photo>
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): static
    {
        if (!$this->photos->contains($photo)) {
            $this->photos->add($photo);
            $photo->setTrail($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): static
    {
        if ($this->photos->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getTrail() === $this) {
                $photo->setTrail(null);
            }
        }

        return $this;
    }

    public function getGpxFile(): ?string
    {
        return $this->gpxFile;
    }

    public function setGpxFile(?string $gpxFile): static
    {
        $this->gpxFile = $gpxFile;

        return $this;
    }

    public function getInputMode(): ?string
    {
        return $this->inputMode;
    }

    public function setInputMode(?string $inputMode): static
    {
        $this->inputMode = $inputMode;

        return $this;
    }

    public function getStartLat(): ?float
    {
        return $this->startLat;
    }

    public function setStartLat(?float $startLat): static
    {
        $this->startLat = $startLat;

        return $this;
    }

    public function getStartLon(): ?float
    {
        return $this->startLon;
    }

    public function setStartLon(?float $startLon): static
    {
        $this->startLon = $startLon;

        return $this;
    }

    public function getEndLat(): ?float
    {
        return $this->endLat;
    }

    public function setEndLat(?float $endLat): static
    {
        $this->endLat = $endLat;

        return $this;
    }

    public function getEndLon(): ?float
    {
        return $this->endLon;
    }

    public function setEndLon(?float $endLon): static
    {
        $this->endLon = $endLon;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->Status;
    }

    public function setStatus(string $Status): static
    {
        $this->Status = $Status;

        return $this;
    }
}

src/Entity/Walk.php
<?php

namespace App\Entity;

use App\Repository\WalkRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WalkRepository::class)]
class Walk
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTime $date = null;

    #[ORM\Column]
    private ?int $max_dogs = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    /**
     * @var Collection<int, WalkRegistration>
     */
    #[ORM\OneToMany(targetEntity: WalkRegistration::class, mappedBy: 'walk')]
    private Collection $walk_registration;

    #[ORM\ManyToOne(inversedBy: 'walks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Trail $trail = null;

    /**
     * @var Collection<int, Photo>
     */
    #[ORM\OneToMany(targetEntity: Photo::class, mappedBy: 'walk')]
    private Collection $photos;

    public function __construct()
    {
        $this->walk_registration = new ArrayCollection();
        $this->photos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    public function setDate(\DateTime $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getMaxDogs(): ?int
    {
        return $this->max_dogs;
    }

    public function setMaxDogs(int $max_dogs): static
    {
        $this->max_dogs = $max_dogs;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, WalkRegistration>
     */
    public function getWalkRegistration(): Collection
    {
        return $this->walk_registration;
    }

    public function addWalkRegistration(WalkRegistration $walkRegistration): static
    {
        if (!$this->walk_registration->contains($walkRegistration)) {
            $this->walk_registration->add($walkRegistration);
            $walkRegistration->setWalk($this);
        }

        return $this;
    }

    public function removeWalkRegistration(WalkRegistration $walkRegistration): static
    {
        if ($this->walk_registration->removeElement($walkRegistration)) {
            // set the owning side to null (unless already changed)
            if ($walkRegistration->getWalk() === $this) {
                $walkRegistration->setWalk(null);
            }
        }

        return $this;
    }

    public function getTrail(): ?Trail
    {
        return $this->trail;
    }

    public function setTrail(?Trail $trail): static
    {
        $this->trail = $trail;

        return $this;
    }

    /**
     * @return Collection<int, Photo>
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): static
    {
        if (!$this->photos->contains($photo)) {
            $this->photos->add($photo);
            $photo->setWalk($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): static
    {
        if ($this->photos->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getWalk() === $this) {
                $photo->setWalk(null);
            }
        }

        return $this;
    }
}

src/Entity/WalkRegistration.php
<?php

namespace App\Entity;

use App\Repository\WalkRegistrationRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WalkRegistrationRepository::class)]
class WalkRegistration
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTime $date_registration = null;
    public function __construct()
    {
        $this->date_registration = new \DateTime();
    }

    #[ORM\ManyToOne(inversedBy: 'walk_registration')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Dog $dog = null;

    #[ORM\ManyToOne(inversedBy: 'walk_registration')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Walk $walk = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateRegistration(): ?\DateTime
    {
        return $this->date_registration;
    }

    public function setDateRegistration(\DateTime $date_registration): static
    {
        $this->date_registration = $date_registration;

        return $this;
    }

    public function getDog(): ?Dog
    {
        return $this->dog;
    }

    public function setDog(?Dog $dog): static
    {
        $this->dog = $dog;

        return $this;
    }

    public function getWalk(): ?Walk
    {
        return $this->walk;
    }

    public function setWalk(?Walk $walk): static
    {
        $this->walk = $walk;

        return $this;
    }
}

src/Form/WalkRegistrationType.php
<?php

namespace App\Form;

use App\Entity\Dog;
use App\Entity\Walk;
use App\Entity\WalkRegistration;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class WalkRegistrationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder

            ->add('dog', EntityType::class, [
                'label' => 'Je souhaite inscrire',
                'label_attr' => ['class' => 'walk-register__desc-title'],
                'attr' => ['class' => 'walk-register__desc-select'],
                'class' => Dog::class,
                'choices' => $options['dogs'],
                'choice_label' => 'name',
                'placeholder' => 'Choisissez votre chien',
                'invalid_message' => 'Sélection invalide.',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => WalkRegistration::class,
            'dogs' => []
        ]);
    }
}

templates/walk_registration/_delete_form.html.twig
<form method="post" action="{{ path('app_walk_registration_delete', {'id': walk_registration.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ walk_registration.id) }}">
    <button class="btn">Delete</button>
</form>

templates/walk_registration/_form.html.twig
{{ form_start(form) }}
<div class="walk-register__desc-item">
	<p class="walk-register__desc-title">{{ form_label(form.dog)}}</p>
	{% set dogsChoices = form.dog.vars.choices is not empty %}
	{% if not dogsChoices %}
		<p class="walk-register__desc-content">
			Vous n'avez pas de chiens disponibles pour la balade.
		</p>
		{% do form.dog.setRendered %}
	{% else %}
		{{ form_widget(form.dog) }}
		<button class="walk-register__button">{{ button_label|default('Valider') }}</button>
	{% endif %}


</div>
{{ form_end(form) }}

templates/walk_registration/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit WalkRegistration{% endblock %}

{% block body %}
    <h1>Edit WalkRegistration</h1>

    {{ include('walk_registration/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_walk_registration_index') }}">back to list</a>

    {{ include('walk_registration/_delete_form.html.twig') }}
{% endblock %}

templates/walk_registration/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}WalkRegistration index{% endblock %}

{% block body %}
    <h1>WalkRegistration index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_registration</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for walk_registration in walk_registrations %}
            <tr>
                <td>{{ walk_registration.id }}</td>
                <td>{{ walk_registration.dateRegistration ? walk_registration.dateRegistration|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_walk_registration_show', {'id': walk_registration.id}) }}">show</a>
                    <a href="{{ path('app_walk_registration_edit', {'id': walk_registration.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_walk_registration_new') }}">Create new</a>
{% endblock %}

templates/walk_registration/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription à une balade
{% endblock %}

{% block body %}
	<section class="walk-register">
		<h1 class="walk-register__title">Valider l'inscription</h1>

		<div class="walk-register__desc">
			<h2 class="walk-register__subtitle">Balade du
				{{ walk.date|format_datetime('full', 'short', locale: 'fr')  }}</h2>

			<div class="walk-register__desc-item">
				<p class="walk-register__desc-title">Itinéraire</p>
				<p class="walk-register__desc-content">{{ walk.trail.name }}</p>
			</div>
			<div class="walk-register__desc-item">
				<p class="walk-register__desc-title">Distance</p>
				<p class="walk-register__desc-content">{{ walk.trail.distance }}
					km{{ walk.trail.distance > 1 ? "s" : "" }}</p>
			</div>
			<div class="walk-register__desc-item">
				<p class="walk-register__desc-title">Durée</p>
				<p class="walk-register__desc-content">{% import 'macros/duration.html.twig' as dur %}
					{{ dur.minutes(walk.trail.duration) }}</p>
			</div>
			<div class="walk-register__desc-item">
				<p class="walk-register__desc-title">Difficulté</p>
				<p class="walk-register__desc-content">{{ walk.trail.difficulty }}</p>
			</div>
			<div class="walk-register__desc-item">
				<p class="walk-register__desc-title">Point d'eau</p>
				<p class="walk-register__desc-content">{{ walk.trail.waterPoint }}</p>
			</div>
			<div class="walk-register__desc-item">
				<p class="walk-register__desc-title">Point de départ</p>
				<div class="walk-register__desc-wrapper">
					<p class="walk-register__desc-content">{{ walk.trail.startAddress }}</p>
					<p class="walk-register__desc-content">{{ walk.trail.startCode }}</p>
					<p class="walk-register__desc-content">{{ walk.trail.startCity }}</p>
				</div>
			</div>
			<div class="walk-register__desc-item">
				<p class="walk-register__desc-title">Point d'arrivée</p>
				<div class="walk-register__desc-wrapper">
					<p class="walk-register__desc-content">{{ walk.trail.endAddress }}</p>
					<p class="walk-register__desc-content">{{ walk.trail.endCode }}</p>
					<p class="walk-register__desc-content">{{ walk.trail.endCity }}</p>
				</div>
			</div>

			<div class="walk-register__desc-item">
				<p class="walk-register__desc-title">Nombre de chien maximum</p>
				<p class="walk-register__desc-content">{{ walk.maxDogs }}</p>
			</div>
			<div class="walk-register__desc-item">
				<p class="walk-register__desc-title">Les chiens inscrits</p>
				<div class="walk-register__desc-wrapper">
					{% if walk.walkRegistration|length > 0 %}
						{% for register in walk.walkRegistration %}
							<div class="walk-register__desc-container">
								{% set dogPhotoClass = ['walk-register__dog-photo', register.dog.sex] | join(' ') %}
									{% if register.dog.photo %}
									<img class="{{ dogPhotoClass }}" src="{{ asset('uploads/images/' ~ register.dog.photo)}}">
								{% else %}
									{{ ux_icon('streamline-plump:dog-1-remix', { class: dogPhotoClass }) }}
								{% endif %}
								<p class="walk-register__desc-content">{{ register.dog.name }}</p>
							</div>
						{% endfor %}

					{% else %}
						<p class="walk-register__desc-content">Aucun chien n'est encore inscrit à cette balade</p>
					{% endif %}
				</div>
			</div>


			{{ include('walk_registration/_form.html.twig') }}
		</div>
		<a class="walk-register__back" href="{{ path('app_home') }}">Retour</a>

	</section>
{% endblock %}

templates/walk_registration/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}WalkRegistration{% endblock %}

{% block body %}
    <h1>WalkRegistration</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ walk_registration.id }}</td>
            </tr>
            <tr>
                <th>Date_registration</th>
                <td>{{ walk_registration.dateRegistration ? walk_registration.dateRegistration|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_walk_registration_index') }}">back to list</a>

    <a href="{{ path('app_walk_registration_edit', {'id': walk_registration.id}) }}">edit</a>

    {{ include('walk_registration/_delete_form.html.twig') }}
{% endblock %}